// AUTO-GENERATED by scripts/gen-city-coords.ts — do not edit by hand.
// Pre-geocoded city coordinates (slug → lat/lng) for the coverage map pins,
// so the map doesn't hit the geocoder at render time. Re-run the script when
// regions change; unknown cities fall back to live geocoding.

export const CITY_COORDS: Record<string, { lat: number; lng: number }> = {
  "amsterdam": {
    "lat": 52.3730796,
    "lng": 4.8924534
  },
  "beijing": {
    "lat": 39.9057136,
    "lng": 116.3912972
  },
  "berlin": {
    "lat": 52.5173885,
    "lng": 13.3951309
  },
  "bogota": {
    "lat": 4.6533817,
    "lng": -74.0836331
  },
  "buenos-aires": {
    "lat": -34.6095579,
    "lng": -58.3887904
  },
  "dallas": {
    "lat": 32.7762719,
    "lng": -96.7968559
  },
  "delhi": {
    "lat": 28.6138954,
    "lng": 77.2090057
  },
  "dubai": {
    "lat": 25.0742823,
    "lng": 55.1885624
  },
  "hanoi": {
    "lat": 21.0283334,
    "lng": 105.854041
  },
  "hong-kong": {
    "lat": 22.2818333,
    "lng": 114.1582831
  },
  "houston": {
    "lat": 29.7589382,
    "lng": -95.3676974
  },
  "jakarta": {
    "lat": -6.1754049,
    "lng": 106.827168
  },
  "karachi": {
    "lat": 24.8546842,
    "lng": 67.0207055
  },
  "kuala-lumpur": {
    "lat": 3.1516964,
    "lng": 101.6942371
  },
  "lagos": {
    "lat": 6.4550575,
    "lng": 3.3941795
  },
  "lima": {
    "lat": -12.0459808,
    "lng": -77.0305912
  },
  "london": {
    "lat": 51.5074456,
    "lng": -0.1277653
  },
  "madrid": {
    "lat": 40.416782,
    "lng": -3.703507
  },
  "manila": {
    "lat": 14.5904492,
    "lng": 120.9803621
  },
  "mexico-city": {
    "lat": 19.3207722,
    "lng": -99.1514678
  },
  "miami": {
    "lat": 25.7741566,
    "lng": -80.1935973
  },
  "mumbai": {
    "lat": 19.054999,
    "lng": 72.8692035
  },
  "new-york": {
    "lat": 40.7127281,
    "lng": -74.0060152
  },
  "newcastle": {
    "lat": -32.9192953,
    "lng": 151.7795348
  },
  "north-carolina": {
    "lat": 35.6729639,
    "lng": -79.0392919
  },
  "ohio": {
    "lat": 40.2253569,
    "lng": -82.6881395
  },
  "paris": {
    "lat": 48.8588897,
    "lng": 2.320041
  },
  "sao-paulo": {
    "lat": -23.5506507,
    "lng": -46.6333824
  },
  "saudi-arabia": {
    "lat": 24.638916,
    "lng": 46.7160104
  },
  "singapore": {
    "lat": 1.2899175,
    "lng": 103.8519072
  },
  "sydney": {
    "lat": -33.8698439,
    "lng": 151.2082848
  },
  "tokyo": {
    "lat": 35.6768601,
    "lng": 139.7638947
  },
  "toronto": {
    "lat": 43.6534817,
    "lng": -79.3839347
  },
  "vancouver": {
    "lat": 49.2608724,
    "lng": -123.113952
  },
  "vienna": {
    "lat": 48.2083537,
    "lng": 16.3725042
  },
  "warsaw": {
    "lat": 52.2333742,
    "lng": 21.0711489
  },
  "zurich": {
    "lat": 47.3744489,
    "lng": 8.5410422
  }
};
