/**
 * Extract the predominant brand colour of every logo in public/logos/ and write
 * lib/logo-colors.ts (slug → hex). The /cases list tints each case band with the
 * matching colour. Re-run whenever logos are added or changed:
 *
 *   npx tsx scripts/gen-logo-colors.ts
 *
 * Algorithm: decode each PNG small, drop transparent + near-white pixels, bucket
 * the rest, and pick the bucket with the best (frequency × saturation) score so a
 * vivid brand colour wins over greys/outlines while mono logos still yield one.
 */
import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const LOGO_DIR = path.join(process.cwd(), "public", "logos");

function toHex(r: number, g: number, b: number): string {
  const h = (n: number) => n.toString(16).padStart(2, "0");
  return `#${h(r)}${h(g)}${h(b)}`;
}

/** HSV saturation in [0,1] — used to prefer vivid colours over greys. */
function saturation(r: number, g: number, b: number): number {
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  return max === 0 ? 0 : (max - min) / max;
}

async function dominantColor(file: string): Promise<string | null> {
  const { data, info } = await sharp(file)
    .ensureAlpha()
    .resize(72, 72, { fit: "inside" })
    .raw()
    .toBuffer({ resolveWithObject: true });

  const channels = info.channels; // 4 (RGBA)
  // Bucket key → { count, r, g, b } accumulator (sums for a true average later).
  const buckets = new Map<number, { n: number; r: number; g: number; b: number }>();

  for (let i = 0; i < data.length; i += channels) {
    const r = data[i];
    const g = data[i + 1];
    const b = data[i + 2];
    const a = data[i + 3];
    if (a < 200) continue; // transparent
    if (r > 228 && g > 228 && b > 228) continue; // near-white (background/halo)
    // Quantise to 5 bits/channel so similar shades merge.
    const key = ((r >> 3) << 10) | ((g >> 3) << 5) | (b >> 3);
    const acc = buckets.get(key) ?? { n: 0, r: 0, g: 0, b: 0 };
    acc.n += 1;
    acc.r += r;
    acc.g += g;
    acc.b += b;
    buckets.set(key, acc);
  }

  if (buckets.size === 0) return null;

  let best: { score: number; r: number; g: number; b: number } | null = null;
  for (const acc of buckets.values()) {
    const r = Math.round(acc.r / acc.n);
    const g = Math.round(acc.g / acc.n);
    const b = Math.round(acc.b / acc.n);
    // Vivid colours beat greys, but frequency still matters for mono logos.
    const score = acc.n * (0.25 + saturation(r, g, b));
    if (!best || score > best.score) best = { score, r, g, b };
  }

  if (!best) return null;
  // A light, low-saturation band (near-white/pale grey) would blend into the
  // white page, so pull its brightness down to a usable tone. Vivid colours
  // (e.g. Shell yellow) are left alone — they read fine against white.
  let { r, g, b } = best;
  const max = Math.max(r, g, b);
  const CAP = 190;
  if (max > CAP && saturation(r, g, b) < 0.4) {
    const k = CAP / max;
    r = Math.round(r * k);
    g = Math.round(g * k);
    b = Math.round(b * k);
  }
  return toHex(r, g, b);
}

async function main() {
  const files = readdirSync(LOGO_DIR).filter((f) => f.toLowerCase().endsWith(".png"));
  console.log(`Extracting colours from ${files.length} logos...\n`);

  const colors: Record<string, string> = {};
  for (const file of files) {
    const slug = file.slice(0, -4).toLowerCase();
    try {
      const hex = await dominantColor(path.join(LOGO_DIR, file));
      if (hex) {
        colors[slug] = hex;
        console.log(`✓   ${slug} → ${hex}`);
      } else {
        console.log(`MISS ${slug} — no opaque pixels`);
      }
    } catch (e) {
      console.log(`ERR  ${slug} — ${(e as Error).message}`);
    }
  }

  const sorted = Object.fromEntries(
    Object.keys(colors)
      .sort()
      .map((k) => [k, colors[k]]),
  );

  const body =
    `// AUTO-GENERATED by scripts/gen-logo-colors.ts — do not edit by hand.\n` +
    `// Predominant brand colour per logo (slug → hex), used to tint the /cases\n` +
    `// bands. Re-run the script when logos change.\n\n` +
    `export const LOGO_COLORS: Record<string, string> = ${JSON.stringify(
      sorted,
      null,
      2,
    )};\n`;

  writeFileSync(path.join(process.cwd(), "lib", "logo-colors.ts"), body);
  console.log(`\nWrote lib/logo-colors.ts with ${Object.keys(sorted).length} colours.`);
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
