/**
 * Pre-geocode every published CMS region's city (city + country → lat/lng) and
 * write lib/city-coords.ts. Runs sequentially with a delay to respect the OSM
 * Nominatim fair-use limit (~1 req/sec). Re-run whenever regions change:
 *
 *   npx tsx --env-file=.env.local scripts/gen-city-coords.ts
 *
 * The coverage map reads this baked table first (fast, no rate limits) and only
 * live-geocodes cities not present here.
 */
import { writeFileSync } from "node:fs";
import { getCoverageRegions } from "../lib/cms/map";

const UA = "CorporateDNA-CoverageMap/1.0 (+https://corporatednaconsulting.com)";
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function main() {
  const regions = await getCoverageRegions();
  console.log(`Geocoding ${regions.length} regions...\n`);

  const coords: Record<string, { lat: number; lng: number }> = {};
  for (const r of regions) {
    if (!r.city) {
      console.log(`•   ${r.slug} — no city, skipped`);
      continue;
    }
    const q = [r.city, r.country].filter(Boolean).join(", ");
    const url =
      "https://nominatim.openstreetmap.org/search?format=json&limit=1&q=" +
      encodeURIComponent(q);
    try {
      const res = await fetch(url, { headers: { "User-Agent": UA } });
      const data = (await res.json()) as { lat: string; lon: string }[];
      if (data.length) {
        coords[r.slug] = {
          lat: parseFloat(data[0].lat),
          lng: parseFloat(data[0].lon),
        };
        console.log(`✓   ${r.slug} — ${q} → ${data[0].lat}, ${data[0].lon}`);
      } else {
        console.log(`MISS ${r.slug} — ${q}`);
      }
    } catch (e) {
      console.log(`ERR  ${r.slug} — ${(e as Error).message}`);
    }
    await sleep(1200);
  }

  // Deterministic key order for a stable diff.
  const sorted = Object.fromEntries(
    Object.keys(coords)
      .sort()
      .map((k) => [k, coords[k]]),
  );

  const body =
    `// AUTO-GENERATED by scripts/gen-city-coords.ts — do not edit by hand.\n` +
    `// Pre-geocoded city coordinates (slug → lat/lng) for the coverage map pins,\n` +
    `// so the map doesn't hit the geocoder at render time. Re-run the script when\n` +
    `// regions change; unknown cities fall back to live geocoding.\n\n` +
    `export const CITY_COORDS: Record<string, { lat: number; lng: number }> = ${JSON.stringify(
      sorted,
      null,
      2,
    )};\n`;

  writeFileSync("lib/city-coords.ts", body);
  console.log(
    `\nWrote lib/city-coords.ts with ${Object.keys(sorted).length} cities.`,
  );
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
